spring:
  application:
    name: student-service
    description:
#  config:
#    import: optional:configserver://localhost:8761
#
#  data:
#    mongodb:
#      uri: "mongodb://localhost:27017"
#      database: student-service-db
#      host: localhost
#      port: 27017
server:
  port: 8087

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    instance:
#      hostname: localhost
