spring:
  application:
    name: gateway-service
    description:
  config:
    import: optional:configserver://localhost:8761

  cloud:
    gateway:
      routes:
        - id: avatar-service
          uri: http://localhost:8081
          predicates:
            - Path=/avatars/**

        - id: element-service
          uri: http://localhost:8083
          predicates:
            - Path=/elements/**

        - id: reward-service
          uri: http://localhost:8085
          predicates:
            - Path=/commands/rewards/**

        - id: reward-service
          uri: http://localhost:8085
          predicates:
            - Path=/queries/rewards/**

        - id: school-service
          -uri: http://localhost:8086
          predicates:
            - Path=/schools/**

        - id: student-service
          uri: http://localhost:8087
          predicates:
            - Path=/students/**

        - id: teacher-service
          uri: http://localhost:8088
          predicates:
            - Path=/teachers/**

        - id: user-service
          uri: http://localhost:8089
          predicates:
            - Path=/users/**





  # data:
  #   mongodb:
  #     uri: "mongodb://localhost:27017"
  #     database: school-service-db
  #     host: localhost
  #     port: 27017
server:
  port: 8084

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
